mass: 0.05        # Wheel mass in Kg
radius: 0.065    # Wheel radius in m
length: 0.060     # Wheel length in m, considering is as a cylinder
mesh: '../components/wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
#mesh: ''
scale: ''
# Offset distance, in meters, from the outer face of the base to the center of the wheel.
x_offset: -0.040
# Offset distance, in meters, from the outer face of the base to the inner face of the wheel. 
# The outer face of the base is the reference so, if the wheels are inside the base the value must be
# negative. If the wheels are outside, must be positive.
y_offset: 0.035
# Offset distance, in meters, from the bottom face of the base to the center of the wheel.
z_offset: -0.042
